### ISSUE TITLE
[TODO] Governments

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#12]
tsf4 and I were talking about what governments to add, and a few ideas cropped up.

Night's Watch: NW will have an elective succession form government, with open voting. Anyone can be elected and, if possible, anyone may vote. Or at the least, barons may vote.

Wildling Government: Allows holding of both tribal and feudal baronies without penalty. This means taking the wall as a Wildling will have no penalty and will allow them to hold it. However, we should block building new holdings.

Any other suggestions?

**Comment by tannerflick4** [comment]
For the NW government, can we make an event which makes a random culture & religion dude from westeros to populate the Lord Commander's court? That way, we dont have a long line of Blackwatermen as LCs. I have no exp with events, but I think its an idea we could (?) implement.

**Comment by RowanMaBoot** [comment]
Issue can be closed for the time being, no particular issues or TODO associated with it.
