### ISSUE TITLE
TODO: Region Overhauls

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#13]
Almaron has been pumping out suggestions for the map, and though the priority isn't high at the moment I'll be sticking everything on the TODO list.

Current looking at (from highest priority to lowest):

- Add Sweetport Sound off the coast of Massey's hook, probably to the west. Non-canon location, so should be a little freedom in location and size (though an island is present on a few maps).
- An overhaul of Dorne.
(http://orig13.deviantart.net/23b1/f/2017/103/f/c/dornetestii_by_amcalmaron-db5qkc7.png)
-- Needs rivers and terrain modification, but is otherwise mostly done.
-- Added three extra provinces during these changes.
- An overhaul of the Vale.
(https://forum.paradoxplaza.com/forum/index.php?threads/wip-the-seven-kingdoms.1003243/page-8#post-22674315)
-- Includes adding of Witch isle, off the coast of Runestone, somewhere to the east. The seat of house upcliff.
- An overhaul of Essos (more cultures, better religious distribution).

**Comment by RowanMaBoot** [comment]
Dorne is in major need of an overhaul, so that will be my priority after the first release. I'm thinking of adding a new terrain type that will increase travel time and may have a little more attrition for the other ways into Dorne to make prince's pass the fastest route (but also the hardest to attack).

**Comment by RowanMaBoot** [comment]
Added the island of 'Sweetport Sound' to the TODO list.

Should be placed off the west coast of Massey's Hook - House Sunglass(?), looking for comments on this location.

**Comment by tannerflick4** [comment]
![image](https://cloud.githubusercontent.com/assets/13467552/25088417/3341622e-2344-11e7-9e89-50291d000b04.png)

Here are 3 suggestions for where it could be. But I like including it!

**Comment by RowanMaBoot** [comment]
I'm thinking around position 1, of a similar length to dragonstone but rotated 90' and probably a little thinner.

Or perhaps just similar to the island directly north of dragonstone (at 11-12 o'clock).

**Comment by tannerflick4** [comment]
I think thats a good position for it. I would go for closer to the size of the island below dragonstone thats really small. What I know is that Sunglass was like all the island could hold.

**Comment by Vierwood** [comment]
I'd recommend you do ahead and overhaul Dorne before I go in and create characters. Best to get it over with.

I'd follow Altemio's map pretty closely. Get rid of the Kingdom of the Boneway and replace it with the Red Mountains, also replace the current Kingdom of The Red Mountains with the Kingdom of The Torrentine.

Rename the duchy of The Red Mountains to The Torrentine.
Create a new kingdom. The Kingdom of Blackmont (Vulture), also for some reason Starfall is in the Blackmon duchy.

**Comment by tannerflick4** [comment]
Something had been nagging me for a while, and so I finally overhauled it: made Beyond the Wall a empire tier title and made around 4 or 5 kingdoms for the wildlings. These changes are reflected in the provinceDef

**Comment by RowanMaBoot** [comment]
@tannerflick4 
I can do a smaller island, that isn't a problem.

@Vierwood 
You mean Almaron's map, right?

I'm a little concerned about the balance of his suggested layout, primarily due to province distribution - so I won't be able to follow it too closely. However, I will _very happily_ spread Dornish provinces out to adjust to border shapes, since they are pretty darn ugly at the moment.

@tannerflick4 
That is great! I completely forgot about them, to be quite honest. The changes should have been included in the recent build. ;)

**To all**
I'm thinking we're going to need to start giving some provinces pre-built holdings. I noticed the difference between the Arbor and Oldtown at the moment, and it is quite startling (although there may be reason for some degree of parity, Arbor currently overpowers them big-time!).

I did a few provinces in the Riverlands, and I think we should look at half, rounded down, of the maximum unless there is good reason for more or less (developed, devastated or just undeveloped per lore). So say 3/6, 2/5, 1/3.

Thoughts?

**Comment by tannerflick4** [comment]
yeah I think half of the max number would be good. of course lorath would really be the only place on our map with devastated holding numbers.

**Comment by RowanMaBoot** [comment]
Dragonstone too, I think.

**Comment by RowanMaBoot** [comment]
Dorne is mostly done. I didn't make too much in the way of changes, so modifying history should be easy enough. Sorry about the hassle Vierwood, call it impulsive editing as I was putting it off but went ahead and did it.

Haven't modified the terrain mesh itself yet, as it that will take some time, so no major rivers. Yet...

**Comment by RowanMaBoot** [comment]
Made some changes to the Vale. Not quite the planned overhaul, largely due to the amount of work that would be required to overhaul it. Plus, I'm actually somewhat happy without it looks at the moment, and I don't want to risk an overhaul.

Added planned Sweetport sound. Was going to add witch isle, but didn't. Might turn one of the tiny isles already on the map (next to gulltown) into it, if it's wanted.

**Comment by RowanMaBoot** [comment]
Made a number of changes, check the commit for more info. Need feedback and thoughts on it - the marshes around the end of the Blue Fork need some touching up, but they show the general idea of what is currently intended.

**Comment by tannerflick4** [comment]
I like the new changes a lot! But still have some suggestions: 1) Iron Islands, Stepstones, & Dragonstone's isles need a bit of height since they are basically big rocks sticking out of the ocean compared to places like Lys or Myr which were low lying fertile flatlands. 2) Duskendale hills seem too high. 3) Should the impassable areas of the Neck be hills? Or were they impassable from marsh? I guess I dont know lol if it was an area protected by marsh & hills or just marshes. 4) For the Trident's source near the coast by the Iron isles, I think it should be hills due to geography (rivers flow down due to going from hills > plains). There are my ideas for now!

**Comment by Vierwood** [comment]
Yeah some elevation at the source would make it more obvious, right now it's kinda flat and weird looking.

**Comment by RowanMaBoot** [comment]
1) Yeah, should be easy enough to do.
2) Duskendale Hill is actually more of a Mountain, and covers a much larger region than just Duskendale - this is kinda common across the map, because otherwise Duskendale would be too similar to the Reach and Riverlands. By no means is it like the mountains in the Vale or the Westerlands, but consider it a similar sort of thing to what is present in the United Kingdom - we traditionally call what Americans would call a hill a mountain.
3) Neck is just very extensive and very dense marshlands. Traditionally such locations are hard to traverse (but by no means lack population, generally full of life). Lore wise the Reeds, for example, now how to easily traverse the region indicating difficulty for others.
4) General idea for the Blue Fork source is the marshlands there, and what presumably could be an aquifer (if I'm using the correct term there) where water 'bubbles up' to the surface. It is also above sea-level, and above the source of the river is there and visible (where it stops).

It looks flat because the texturing is awful.

**Comment by RowanMaBoot** [comment]
Cleaning up this issues, as there are currently no plans for future overhauls of any particular regions; just incremental improvements over time. If anyone has any suggestions for major changes or improvements, feel free to re-open the issue.
