### ISSUE TITLE
BUG(?): provinceDef.xls

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#15]
We have a major bug. For some reason the map filler tool is **_not_** working correctly. It compiles, but many provinces are not being read from correctly.

Dragonstone and The Arbor are two examples, which fail to build correctly when changes are made to the number of prebuilt holdings despite no given errors.

This is a problem, because this issue could be more widespread than is currently realized, as it may be related to formatting, a broken cell, row or column.

**Comment by RowanMaBoot** [comment]
It seems to be related to the use of (C) (B) and (T), needs further testing. This could be a tool related issue, or a benign difference in character related to a different keyboard, settings or some very obscure issue, as it does not appear to be universal.

In the case of the Arbor, every holding is assigned and there are no temples, it may be trying to include at least one temple as it is the last building.

- Switching around (T) with a (C) did not make a difference.
- Removing all assignments fixed the issue.
- Manually replacing all assignments with instances created via my keyboard led to the return of the issue.
- Manually assigning UP to Grapevyne (T) 4/6 fixed the issue, however, setting Mermaid's Palace (B) in slot 5/7 led to the return of the issue.
- Switching Grapevyne (T) 4/6 with Mermaid's Palace (B) 5/6 so that Grapevyne sits in position 5/6 with no assignment solves the issue once again.

However, setting so that one holding is built out of seven for the Arbor, we run into a lovely issue. Any holdings that have been awarded an assignment are pre-built for some reason.

This may not actually be a bug, but intended. However, we are going to have to work around this.

**Comment by RowanMaBoot** [comment]
Okay, it doesn't appear to be a bug per sey, but an oversight.

The author intended that (B), (C), (T) results in prebuilt holdings without taking into account the possibility that we may want to assign the type to non-prebuilt holdings.

We're going to have to remove instances of (B), (C), (T) from extra holdings beyond the prebuilt threshold, otherwise we'll start with more built than intended (dragonstone is a good example).

**Comment by tannerflick4** [comment]
Yeah I have found the tool's use of those letters is not very good at all. I prefer not to use them, but I know they are necessary for our world (but are they?).

**Comment by RowanMaBoot** [comment]
Well, the problem is the tool generates by defaults a fixed order of castle city temple castle city temple castle, which leads to name mismatch in some cases and well... Who wants two temple baronies?

For the most part we're going to have to remove the assignments though. If we're only generating 4_7, so only 4 should be assigned. Going to take some time to go through, so yippy!

**Comment by tannerflick4** [comment]
I don't see a need to remove baronies though. Can't we just switch names up to work with the default output you stated? And I can help if you would like.

**Comment by RowanMaBoot** [comment]
By remove baronies, I mean remove the (B), (C), (T)

The problem is, having some random provinces generate every single holding is a bad thing when we are balancing it so only 1_6 generates, for example.

**Comment by tannerflick4** [comment]
Oh ok. That makes sense.

**Comment by RowanMaBoot** [comment]
I've cleaned up most of these cases, I think.
