### ISSUE TITLE
ISSUE/TODO: In working Order

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#16]
To call the mod functional might actually be far from the truth. I've tried running the mod for a few decades, and though it works (very quickly) it eventually crashes. I dug through the logs and discovered a lot of errors, so grabbed the validator and had a peek.

And oh my is it daunting.

I'll put it like this. We no longer have Vanilla cultures, religions or titles. Many events, decisions and traits reference them. So I stripped many of the events and decisions in an attempt to deal with this. However, many other files - decisions, on_actions - reference these events.

Getting an idea of the problem? D:

So I've re-added all of the Vanilla events. For now. I think we will need to comb through every event, find their ID, do a recursive search through the mod for references to that ID and then strip those references. Then we can clear out the event and move onto the next.

It took over an hour just to go through cb_types, and I hope by the seven that I managed to clear it up without breaking or removing anything important.

**Comment by thestonedigger** [comment]
Oh god... This will take a fucking while to finish

**Comment by RowanMaBoot** [comment]
Closing for now.
