### ISSUE TITLE
[IMPORTANT] When Editing 'ProvinceDefs.xls'

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#2]
If you're editing the ProvinceDefs.xls, pop a post here.

When you're done with it, please upload the changes you've made and pop another message here - the file is kinda pain as we are unable to merge changes made by different users!

Please don't hold onto the file for longer than you need. If you've got to step away for a few hours, or you're off to sleep for the night please upload it! We don't want to accidentally overwrite changes and put us in a position where we need to redo any overwritten changes.

**Comment by RowanMaBoot** [comment]
I'm going to reserve ProvinceDefs.xls to make changes in the free cities. 6/3/17 - 11:55AM, Central US

**Comment by RowanMaBoot** [comment]
Finished editing Braavos, file is free for anyone to edit. 6/3/17, 13:33PM, Central US

**Comment by tannerflick4** [comment]
I'll reserve it for 15:00PM to 16:000PM, Eastern US, to make changes in the Vale.

**Comment by RowanMaBoot** [comment]
Reserving 16:00PM EST to 16:10PM EST to merge in changes; added ocean provinces to the map. Initial upload already done.

**Comment by tannerflick4** [comment]
Added some names to south and eastern vale. Free to edit now.

**Comment by RowanMaBoot** [comment]
Merged the Ocean provinces into the latest version, file is free for anyone to edit now.

**Comment by RowanMaBoot** [comment]
Reserving 16:30 EST to 17:00 EST to make edits to Braavos.

**Comment by RowanMaBoot** [comment]
Edits finished, Moonsinger holy sites have been added. File is free to edit.

**Comment by tannerflick4** [comment]
Reserving 18:00 to 18:30 EST for more Vale edits.

**Comment by tannerflick4** [comment]
Ok added some names to central vale. Free to edit now.

**Comment by Vierwood** [comment]
Added some Riverland provinces

**Comment by Vierwood** [comment]
Reserving 5:45-6:45 pm EST Tomorrow

**Comment by RowanMaBoot** [comment]
****Just an FYI

Make sure you sync before you begin editing! All the changes tannerflick4 and I made were overwritten by your latest Commit Vier. Make sure you sync and refresh in the future to make sure you have the latest file! No biggy as we can easily revert. ;)

(Vier is manually merging his changes back into the master, he didn't have Github set up correctly - all sorted!)

Oh, loving the names you've got going on in the Vale tanner ;D

**Comment by tannerflick4** [comment]
Reserving the file from 8:00-9:00 EST

**Comment by tannerflick4** [comment]
free to edit now. put the wrong reserve hour lol :)

**Comment by tannerflick4** [comment]
reserving file from 12:00 - 13:00 EST

EDIT: free now. And, by the way, I am not sure on the holding slots so someone can make sure they are good.

**Comment by RowanMaBoot** [comment]
I'm going to reserve the file from 13:00 -> 14:00 EST

@tannerflick4 
Holding numbers look fine to me! They're something we can mess with in the future if they feel off in any way, but given the number of provinces they have (one of the smaller LPs), it all looks good to me.

**Comment by RowanMaBoot** [comment]
Free to edit.

Lorath done, latest mod version built with tannerflick's changes (and mine too).

**Comment by tannerflick4** [comment]
reserving file from 15:00-16:00 EST

**Comment by tannerflick4** [comment]
Free to edit. Finished duchy and prov names for the North and finished prov names for the Wall.

**Comment by Vierwood** [comment]
Reserved 7-8pm EST

**Comment by Vierwood** [comment]
Done, finished the Riverlands.

**Comment by Vierwood** [comment]
doing some work in the Reach until 9:30pm EST

**Comment by tannerflick4** [comment]
reserving for some beyond the wall work from 9:00 - 10:00 EST

**Comment by tannerflick4** [comment]
free to edit - added beyond the wall and andalos stuff

**Comment by tannerflick4** [comment]
reserving file from 12:00 - 13:00 EST

**Comment by tannerflick4** [comment]
free to edit - finished andalos, pentos, and started myr (duchy and prov naming)

**Comment by tannerflick4** [comment]
reserving file from 15:00 - 16:00 EST

**Comment by tannerflick4** [comment]
free to edit - finished myr, tyrosh, and half of lys (duchy and prov naming)

**Comment by RowanMaBoot** [comment]
Holy damn, you're on fire! Going to need to see what is left for me to do in a bit. ;D

**Comment by Vierwood** [comment]
Reserved 5:45-6:30pm EST

**Comment by Vierwood** [comment]
Reserved until 9:30pm EST

**Comment by RowanMaBoot** [comment]
Some late night edits. Will reserve regardless, from 1AM EST to 2:30AM EST.

**Comment by RowanMaBoot** [comment]
Free for anyone to edit. =D

**Comment by tannerflick4** [comment]
Reserving file from 12:00 - 13:00 EST

**Comment by tannerflick4** [comment]
Free to edit - finished up lys and stepstones and added a tiny few names to dorne (duchy and prov names)

**Comment by RowanMaBoot** [comment]
Going to reserve 13:45 EST - 14:45

Will do a full mod build afterwards. Just going to get some of the holy sites sorted (rhllor), set up the coastal provinces in Essos be republics. Will also probably do some tweaks here and there and add some names too.

Oh, and if you want to post any screenshots on the main thread tanner, feel free to do so! I'm guessing you'll want to wait for the next build tho. :)

**Comment by RowanMaBoot** [comment]
I've finished what I need to do, so free to edit.

Currently getting the latest build sync'd, make take a little while as I've regenerated every single flag, so no more blank banners with question marks.

**Comment by tannerflick4** [comment]
Once you get the build sync'd, I'll reserve the mod for pics and more work for 15:00-16:00.

**Comment by RowanMaBoot** [comment]
Should be up now!

**Comment by tannerflick4** [comment]
Free to edit - posted pics and spotted some of dorne's big towns

**Comment by Vierwood** [comment]
Reserved until 7:30pm EST

**Comment by tannerflick4** [comment]
Reserving from 9-10 EST

**Comment by tannerflick4** [comment]
Free to edit - finished Dorne duchy and prov and did a few for stormlands

**Comment by ExCrisis** [comment]
Reserving from 12 EST to about 1:30 EST

**Comment by ExCrisis** [comment]
Free to edit. Have to step away suddenly so stopping early.

**Comment by Vierwood** [comment]
Reserved until 7:00pm EST Gonna grind out the Stormlands

**Comment by Vierwood** [comment]
Done with the Stormlands, free to edit

**Comment by RowanMaBoot** [comment]
6:11 PM - Vierwood: ive got better names m8
6:11 PM - Яowan: then u do it
6:12 PM - Vierwood: nah

wow.

Reserving from 19:20 EST until 20:00. Going to burn everything Vierwood has done in the last twenty-four hours as a show of power, and will imprison his family in the darkest dungeons of Westeros for claiming his names are better than mine.

Also known as doing the Crownlands and whatever else might need doing.

**Comment by RowanMaBoot** [comment]
Extending a little, until 20:30, will be done before then I wager. Ran into some bugs and other issues, concerning Duskendale (two instances of, neither where Duskendale actually was, and the real one hadn't been touched!) and Tarth. Fixed them all, so we should be good.

**Comment by RowanMaBoot** [comment]
Free to Edit.

**Comment by Vierwood** [comment]
Jesus, you're evil.

Anyway Tanner you can finish off the Dusklands... After that the fun begins.

**Comment by tannerflick4** [comment]
Reserving for 9-10 EST

**Comment by tannerflick4** [comment]
Question: When making names for the baronies, we just want 2 if for example its 1_2? Because even if players build more through the prosperity mechanic they will still have winterfell_4, 5, 6...

**Comment by tannerflick4** [comment]
free to edit

**Comment by RowanMaBoot** [comment]
Awesome work guys! :D

@tannerflick4 

I think so. I've not played with the prosperity mechanic, so I'm not sure how it works. If that is how it works, then I think that is what we need to do.

**Comment by tannerflick4** [comment]
Sounds good. Reserving file from 3-3:45 EST

**Comment by tannerflick4** [comment]
reserving file for 9-10 est

**Comment by tannerflick4** [comment]
reserving file from 15-16 EST

**Comment by RowanMaBoot** [comment]
Reserving the file from 19:00 EST -> 19:30 EST to make some tweaks and fixes.

**Comment by RowanMaBoot** [comment]
Free to edit, didn't need make any changes. Just some ghost files left over.

**Comment by tannerflick4** [comment]
reserving file from 9-10 est

**Comment by tannerflick4** [comment]
free to edit

**Comment by tannerflick4** [comment]
reserving for now till 13:00 est

**Comment by tannerflick4** [comment]
Stop me if we don't need to post this everytime, but reserving from 15-16 est

**Comment by RowanMaBoot** [comment]
Reserving is fine if you're editing the provinceDef.xls file, or if you're editing the history files of a specific region to avoid conflicting edits. I'm working on Braavos, so I suggest noone touches it! ;D

**Comment by tannerflick4** [comment]
Reserving for barony naming from 9-10 est

Free to edit now.

**Comment by tannerflick4** [comment]
Reserving for barony naming from 12-13 est

**Comment by tannerflick4** [comment]
Reserving for naming from 15-16 est

**Comment by tannerflick4** [comment]
Free to edit

**Comment by tannerflick4** [comment]
Reserving from 9-10 est. Also, reopening until we are truly done using this file.

**Comment by RowanMaBoot** [comment]
We'll still be working with this file for a while longer for cultures, religions and holy sites. But not long until we can shove it out of sight and mind! ;D

Reserving the file myself from 4PM EST - 5PM EST

**Comment by RowanMaBoot** [comment]
Once again reserving, 8pm EST - 9pm EST

**Comment by RowanMaBoot** [comment]
Free to edit.

**Comment by RowanMaBoot** [comment]
Reserving from 24:00 EST - 01:00 EST

**Comment by RowanMaBoot** [comment]
Free to edit.

**Comment by tannerflick4** [comment]
Reserving for some changes to prov names in the north, for a few minutes.

**Comment by tannerflick4** [comment]
free to edit

**Comment by tannerflick4** [comment]
changed moat cailin so that its the cap of its duchy

**Comment by tannerflick4** [comment]
reserving this from 15-16 est

**Comment by tannerflick4** [comment]
reserving for barony work from 11-12 est

**Comment by tannerflick4** [comment]
Scratch that. Just going to work on chars and buildings.

**Comment by tannerflick4** [comment]
Reserving for 15-16 est

**Comment by tannerflick4** [comment]
free

**Comment by RowanMaBoot** [comment]
Reserving ~2PM EST - 3PM EST

**Comment by tannerflick4** [comment]
reserving from 15-16 est

**Comment by tannerflick4** [comment]
reserving for 13-14 est

**Comment by tannerflick4** [comment]
reserving for 9-10 est

**Comment by tannerflick4** [comment]
reserving from 13:30-14:00 est

**Comment by tannerflick4** [comment]
reserving for 9:30-10:00 est

**Comment by tannerflick4** [comment]
reserving for 3-3:20 est

**Comment by tannerflick4** [comment]
finished. if someone needs it I can upload it, but otherwise uploading at 4.

**Comment by tannerflick4** [comment]
barony work from now till whenever I post that its free

**Comment by tannerflick4** [comment]
free to edit

**Comment by tannerflick4** [comment]
barony work from now till 17:30 est

**Comment by tannerflick4** [comment]
free

**Comment by tannerflick4** [comment]
barony work till 5:30 est

**Comment by tannerflick4** [comment]
free

**Comment by tannerflick4** [comment]
barony work from 17:00 est - 17:30 (starting in 20 minutes)

**Comment by tannerflick4** [comment]
barony work from now to 17:30 est

**Comment by tannerflick4** [comment]
barony work from 11-11:30 am est

**Comment by tannerflick4** [comment]
barony work from now till 9:30 am est

**Comment by tannerflick4** [comment]
barony work from 15-16 est

**Comment by tannerflick4** [comment]
since git was being screwy, no work done here. free to edit

**Comment by tannerflick4** [comment]
reserving from 11:00-11:30 am est

**Comment by ZeroFighterR** [comment]
reserving from now till next hour. Have to do a lot of cleanup.

**Comment by ZeroFighterR** [comment]
free to use again

**Comment by tannerflick4** [comment]
reserving from now till 10 pm est

**Comment by tannerflick4** [comment]
ok actually its free

**Comment by tannerflick4** [comment]
reserving from 11-11:30 am est

**Comment by RowanMaBoot** [comment]
Reserving 2:30-3:30 EST

**Comment by RowanMaBoot** [comment]
Free to edit
