### ISSUE TITLE
Jade Dragon Features for the Valyrian Freehold

### ISSUE THREAD

**Issue by DeveloperAmr** [Altemio/SevenKingdoms-master#25]
I think, if you check out the jade dragon features for china and how it works, it would be great to implement it as a way to interact with the valyrian freehold. Basically go check out the Jade dragon features and videos and you can see how we can possibly implement it to work with the valyrian freehold

**Comment by Vierwood** [comment]
We have already planned to do this.

**Comment by RowanMaBoot** [comment]
Covered in an existing issue: https://github.com/Altemio/SevenKingdoms-master/issues/24

Please read existing issues before posting duplicates. ;)
