### ISSUE TITLE
[TODO] Psychology/Congenital Overhaul

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#26]
A few ideas I've had bubbling. Nothing too complex at the moment, and probably a little too much -- but it could be worth trying out. I'll look into it down the line, just getting it down here for the time being. Traits won't need icons, as I'd like to keep these ones hidden.

Basically I'd like to introduce hidden psychology traits in the way of sliders, with values of one to five (or one to ten, with five being a balanced state). Their level would influence the chance of getting certain traits during childhood, and have varying effects on skills.

I'm not sure how good of an idea they would be in regards to performance, and if they should be assigned on birth or during development. Parents should logically have the biggest impact, but guardian could influence too.

- Intelligence (A walking vegetable versus Einstein)
- Empathy (Cruelty and apathy versus innate understanding and compassion)
- Extroversion (Versus introversion, would encourage different lifestyle/personality traits - shy versus gregarious and so on)
- Rationality (Irrational characters might be very zealous, and prone to extremes whilst rational characters would be very moderate, and likely just).

Could add more to that list, not entirely sure if it'd be best to though. As said before, just an idea. Thoughts?

**Comment by sens1r** [comment]
A few thoughs in no particular order.

- Does every character start balanced? If not we'd need to be careful when assigning these so it doesn't wreck an entire house for generations.
- I believe guardians should have a significant impact, this could be a useful mechanic to save your heir if one of the parents is looney.
- Values should probably be assigned during development.

In general I think it'sa  good idea, it makes for a more personalized heir and a greater feeling of continuity if implemented correctly. I guess the hard part here will be to balance the possible outcomes so it doesn't tilt the characters too far in either direction.

**Comment by Vierwood** [comment]
Yeah the traits should resemble a bell curve, almost everyone would be considered average with only a few outliers. (Few means a few hundred)

**Comment by RowanMaBoot** [comment]
Some good points! Didn't consider long-term impact, however I guess if we do have a good degree of nuture that can overcome nature, it should be possible (even if it takes multiple lifetimes) to deal with 'negative' values.

A good degree of intelligence should probably be assigned on birth, but I think the other three proposed values could indeed be assigned during development as they are significantly more nurture oriented than nature.
