### ISSUE TITLE
[TODO] Magic

### ISSUE THREAD

**Issue by Madcliff** [Altemio/SevenKingdoms-master#28]
Currently implemented, first steps of flame based magics, need to balance. Includes the basic spellbook system that lets dynamic expansion of known spells. Also includes a comprehensive mechanism to determine whether or not a spell should take effect, this includes a dispel/mechanism, a mechanism whereby each spell needs to reach a required value to be a valid cast, and a mechanism for losing control of a spell and suffering negative consequences. 

Currently also supports multiple types of magic, and as a result is possessed of multiple spell books so to speak. Each spell can be limited to be acquired by doing a unique and individual task. There is also a split between magic fit for war, and magic more focused on controlling and effecting characters. 

Currently has four spells for combat implemented, which are themed and based around fire. Also demonstrates a scripted damage over time effect. 

Currently to be implemented is a variation of divination, based on a fusion of some newer code of mine and the hermetics scrying decision. Will also include multiple effects and a more random determination for the power and potency of the effects. Will be moving the use of flags to instead using stacking invisible modifiers, and moving from a self targeted decision to being a targeted decision that affects a subject. This change in orientation will let your spell take effect for someone else or indeed yourself. Thematically, this will take the form of you showing your victim things, and based on your prior selections this will push them down a positive or negative path. You get to choose what sort of relations things will have. 

Suggestions are welcome for more effects. 

Planned/suggested areas of magic, are Fire, Blood, Water, Shadow and a fifth non specific alchemy orientated art of magic. Perhaps also including a mental/foresight orientated branch too.

**Comment by Vierwood** [comment]
So who exactly is going to be able to wield magic? Would it be the Red Preists and Children of the Forest?

**Comment by Madcliff** [comment]
To be honest I am not entirely sure. At the moment I am linking magic to societies but that can change really at any time there is a better suggestion.

**Comment by RowanMaBoot** [comment]
We'll need a number of societies for the magic system, either as a place to learn or to serve as a collective source for magic. Couple of ideas below - these societies would have magical powers. Need one for the Rhllor magic users.

- Faceless Men
- The Greenseers
- Drowned God Society (Need  name, really primitive water magic - scrying, maybe resurrection)
- Conclave of Shadows (Generic Shadow-born magic, maybe for the Wildlings, Pirates or similar)

**Comment by Madcliff** [comment]
I am currently planning on six magic societies. One for each of triad of elemental magics, one each for blood and shadow magics and then one which is a higher learning, for those who seek to find magic in all of it's forms and seek things like potions and artifact making. This sixth society would be in essence like a precursor to Maesters with the Valyrian link to their chains.

**Comment by RowanMaBoot** [comment]
Sounds great to me! Going to make the Knightly Order of the Seven fairly mundane in comparison!
