### ISSUE TITLE
TODO: Cultures

### ISSUE THREAD

**Issue by Vierwood** [Altemio/SevenKingdoms-master#3]
**Leave suggestions for new cultures.**

Culture - Duchy/Region

Example:

Tarthman-Tarth

**Comment by Vierwood** [comment]
Waterman - Wendwater
Marchman - Nightsong/Blackhaven
Manderish - Cider Hall/Mander
Copperlander - Copper Hall
Craggon - The Crag
Goldman - Goldshire
Muddish - Oldstones
Bronzeman - Runestone
Sisterman - The Three Sisters
Salt, Stone, Sand Dornish - Dorne

**Comment by RowanMaBoot** [comment]
Going to note here what I said in steam;

Bronzeman, Sisterman are both good, especially since they cover very specific areas. I'd say Muddish rather than Mudmen, personally, as it helps break up the universal -man suffix going on in the world.

Cragman could be shifted to something like Craggon, maybe to reflect that it is a foreign (original) culture.

**Comment by RowanMaBoot** [comment]
Wildlings probably should have some extra love. Not following the names of clans (but they could be), but an attempt at giving them some cultures. Thenn and Skagosi is in there, not as a suggestion but as a comparison point.

I don't know the names of any of the canon culture groups, so I've gone and spewed these out. Could put a few more here, but I'd like to get an idea of what canon ones we need to add first and what modifications we might want to make to their names, if any at all.

Gildlic - Beyond the Wall
Dumhic - Beyond the Wall
Skagosi - The North / Skagosi Isles
Hartenn - Hartenns - Beyond the Wall
Thenn - Thenns - Beyond the Wall
Saliosi- Beyond the Wall
Harishic - Beyond the Wall

**Comment by tannerflick4** [comment]
Some extra wildings that are canon:

Cave dwellers (frigid highlands), Hornfoots, Ice rivermen (/frozen marshes/great lakes), men of the frozen shore (chariot rider people), Nightrunners

Hill clans of the North - northern clans duchy

Orphans of the Greenblood could be given a duchy in Dorne. They came over with Nymeria but refused to assimilate into Dornish culture.

**Comment by Vierwood** [comment]
I like the Orphans of the Greenblood idea.

**Comment by RowanMaBoot** [comment]
All cultures added now!

I've added localisations too whilst I was at it. Still need to give all of them unique colours, which I will do later. This goes for religions, too.

Gotta pop out, will list all culture reference names later.

**Religion reference names:**

```
the_seven
the_seven_gods
the_mother
the_stranger

lady_of_the_shore
old_gods
old_gods_beyond
old_gods_beyond_white

drowned_god
storm_god

rhllor
moonsingers
faceless_men

valyrian
the_dragon_gods
eastern_pagan_group
the_weeping_lady
lady_of_the_rocks
```

**Comment by RowanMaBoot** [comment]
**Culture reference names:**

```
thenn
nightrunners
frozen_shore
ice_rivermen
hornfoots
cavemen
gildlic
dumhic
hartenn
saliosi
harishic
skagosi
wildling
northmen
barrowmen
flint_clansmen
crannogmen
hill_clansmen
clansmen
crackclawmen
dusklander
mountain_clansmen
craggon
muddish

andal
valeman
lowland_valeman
bronzeman
sisterman
crownlander
riverlander
westerlander
goldman
copperlander
cornlander
reachman
shieldislander
manderish
wynelander
stormlander
marcher -- (Dornish Marshes)
waterman
wrathman
rainlander
rhoynar
dornish
salt_dornish
sand_dornish
stone_dornish
scorched_dornish

orphans_of_the_greenblood
```

**Comment by Vierwood** [comment]
Tarthman / Tarth

**Comment by Vierwood** [comment]
Northmarcher / Northmarch -Reach

**Comment by Vierwood** [comment]
Fair Islander / Fair Isle

**Comment by RowanMaBoot** [comment]
I think both Fair Isle and Tarth are too small to have unique cultures, as those cultures would not make sense outside of said islands. Ideally the culture should encompass multiple duchies at the least, or partially pour into neighbouring provinces.

Like Goldman can fit into a number of duchies, not just Goldshire but other regions around the gold road. Copperlander can also cover a sort of wider area than just copper hall, if that makes sense.

**Comment by Vierwood** [comment]
Those cultures would also appear on the coast nearest to the island, also they should have a unique culture since they mostly live in isolation on the island. Also North Marcher would encompass Tumbleton and possibly the county of Payne Hall.

**Comment by Vierwood** [comment]
Clawman - The Bay of Claws

**Comment by tannerflick4** [comment]
Are we good with this issue? I like the way we have our cultures set up.

**Comment by RowanMaBoot** [comment]
I think we're good on cultures, for now!
