### ISSUE TITLE
[MAJOR] Jade Dragon - Update

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#30]
**The mod is now functional with the Jade Dragon release as of 14/1/18.**

Most of the issues were solved, due to extensive bug fixing by everyone, but a critical crash on setup was preventing testing and play. Vierwood accidentally found the cause when testing ARKO with the mod, and it turned out to be an issue with core interface references being missing from our main.gui (which was modified for the custom mini-map).

We've still got a lot of work to do, mostly in the realm of bug fixing and polishing, which I will be focusing on when I've got free time. The error logs are huge, so please check them out if you've got any time or feel bored enough to hammer away at it.

To also note, I've now purchased most of the DLCs, so I'll be able to focus better on DLC mechanics (like way of life) and hopefully improve some of the less develop aspects of the mod.

**Comment by tannerflick4** [comment]
I have sifted through and fixed many of our historical errors, although unable to digest some of the more mind-boggling errors unrelated to char history.

**Comment by blackninja9939** [comment]
Pretty much all the errors are self explanatory as to the issue.

Removing events is a poor idea as adding them back in is a pain in the arse, just comment them out with `#` in front of every line in the file.

Crash on start look at the setup log it might point you in the direction of where things started failing to load.

**Comment by RowanMaBoot** [comment]
Unfortunately I haven't yet been able to discern exactly what is causing the crashing, because loading gets to ~99% before throwing an exception and creating a dump.

Setup and error logs haven't been clear as to what the cause might be, but it is difficult at this point due to the current state of the error log (I've already managed to reduce it by some thousand or two lines, but a long way to go yet.
 
An identical crash is caused when entering ruler designer.

**Comment by ZeroFighterR** [comment]
I spent a couple days ago fixing many issues concerning character traits. Is there still an issue with that?

**Comment by Vierwood** [comment]
I fixed most of the history issues, the ones remaining shouldn't cause any issues. One thing I noticed was that the title e_china_west_governor has no holder, I fixed this locally, but it did not stop the crash at 99%.

**Comment by tannerflick4** [comment]
I am trying to enlist Zara (a guy I work with on other mods) to help figure out and solve our crash at 99% loading. He is going through a tough time IRL, but I am reminding him every day. He managed to fix the Faerun mod (which we are both a part of)'s crashing, so he thinks this will be a relatively simple fix.

**Comment by Vierwood** [comment]
Good to hear, the sooner the better.

**Comment by RowanMaBoot** [comment]
If he'd like to help, pop me his details (Github name) and I can give him access to this Github repo. Any help would be greatly appreciated!

**Comment by ZeroFighterR** [comment]
@Vierwood I changed that locally to the valyrian freehold (as it should be). I think the problem is related to the long list of problems around traits with the unknown trigger-type. I have no idea what is causing that and I'm unable to find anything related to it.

**Comment by blackninja9939** [comment]
What are the errors exactly? Most of them should be decently clear in what is incorrectly being checked

**Comment by ZeroFighterR** [comment]
This is the complete log of what's all wrong.
-snip-

**Comment by blackninja9939** [comment]
I am not exactly sure what the confusion is then? Pretty much all those errors are entirely self-explanatory.

eg: 

- [trigger.cpp:2257]: Unknown trigger-type: "is_devil_worshiper_trigger" at
You are using this scripted trigger incorrectly to the point where even the debugger is not sure what is going on. Go through all your files and fix the uses of it.

- [onaction.cpp:209]: OnAction list is referencing invalid event! event: "RIP.10031", on_action: "on_decade_pulse"
Your on actions are referencing an event you have removed or commented out

- [persistent.cpp:40]: Error: "Undefined modifier type! token: zoroastrian_opinion, near line: 779" in file: "common/artifacts/00_artifacts.txt"
You are using an opinion type you no longer have in the mod

**Comment by ZeroFighterR** [comment]
I knew about most, I was just unaware where I should start looking to fix the tigger-type problems.

**Comment by RowanMaBoot** [comment]
Yeah, the logs are very easy to understand - one thing I like a lot about CK2 in general is how robust the logging is. However, our crash cause isn't and hasn't been logged so far, probably because it's somewhat unusual (in that expected, hardcoded elements weren't present).

Appears the issue has been caused by Jade Dragon UI elements being missing from the main.gui file, so the mod may full well launch. If anyone wants a try, please report back here if it's the case. If not, then a little more investigation is needed but we're on track as Vierwood's commit that temporarily integrated ARKO (reverted until permission, was just because the crash disappeared) solved the crashing.

**Comment by RowanMaBoot** [comment]
tsf4 has confirmed the mod now works!! Big thanks to Vierwood for catching the issue, accidental or otherwise, because it narrowed down the issue - and huge thanks to blackninja for his patience and for taking the time to give help and advice and to everyone for all the work you've been putting into our baby. :)

If you guys get any time to play, would be good to get a good stability run and see how things are all working. We can now also look to JD feature integration and the sort now, which is awesome! I'll be dog tired after a 13 hour day tonight, but I'll see if I can get some playtime and modding it too.

**Comment by ZeroFighterR** [comment]
Good to hear that it's working again

**Comment by Vierwood** [comment]
@blackninja9939 do you know where the Jade Dragon localisation is? I can't find it anywhere.

**Comment by blackninja9939** [comment]
JadeDragon.csv

**Comment by RowanMaBoot** [comment]
@ZeroFighterR Oiiiii what happened to you? You seem to have dropped me from your friends list and have dropped from the steam group? Everything all right?

**Comment by ZeroFighterR** [comment]
@Altemio Yeah, I gave my steam account to my younger sister because I barely have time to actually use it because of work. Looks like she removed all my friends and left all the groups. I'm still in TS to contact though.

**Comment by RowanMaBoot** [comment]
Ah okay, fair enough! Kinda in the same boat, both are my sisters are basically using my account all the time, whilst I rarely touch it.

**Comment by Vierwood** [comment]
We're getting the same 99% crash now.

**Comment by ZeroFighterR** [comment]
Might start by cleaning up the error log. It's even filled with more errors than before.

**Comment by RowanMaBoot** [comment]
@Vierwood do we have any idea as to when the issue started, or which commit caused it?

[From Work]

**Comment by Vierwood** [comment]
@Altemio I think it might have been caused by one of the commits by Tanner. I'm not sure which one. It's the same 99% crash so it most likely has to do with the gfx.

**Comment by RowanMaBoot** [comment]
@Vierwood 

https://github.com/Altemio/SevenKingdoms-master/tree/2f8b7ab206ec63a53bad22af3060afe557d6000c
https://github.com/Altemio/SevenKingdoms-master/tree/0efbbec3fdd05e81b20041620867741fc8d65720

You can click on commits, the identifier, then go to specific repo states. Suggest going to the above two states, downloading manually from site, and then testing to see if they crash or not. Suspect it has nothing to do with GFX, but with issues relating to the offmap power/s.

[From Work]

**Comment by Vierwood** [comment]
I'll test those tonight.

**Comment by Vierwood** [comment]
@Altemio neither of them work.

**Comment by RowanMaBoot** [comment]
It's the Off Map powers causing the crashes. Suggestion would be to manually split off the off-map powers into a 'sub-module' so to speak, which can be merged into local builds for testing so we can at least have a functional/playable master build to try other stuff out on.

https://github.com/Altemio/SevenKingdoms-master/tree/6fcf47b153474872e8c0711344329acc665a1d5f

That build is from prior to all of the Off-map power stuff, post interface fix.

**Comment by Vierwood** [comment]
I can confirm that the mod runs with Jade Dragon now. I'll let it run for as long as possible later.

**Comment by RowanMaBoot** [comment]
Was just a few missing brackets and a typo in the offmap powers txt file, so great we managed to fix it without reverting any of the work tanner did :)

**Comment by Vierwood** [comment]
The game seems to crash within a couple of years in. Most likely caused by an event.

**Comment by Vierwood** [comment]
@Altemio @tannerflick4 I think the crash has to do with an event in JD. When I turn the DLC off the mod runs fine for decades.

**Comment by RowanMaBoot** [comment]
How is the mod running at this point? Decent stability, or are we still seeing crashes? And any bugs or issues?

Known:

- Byzantine events firing during play.

**--From Work**

**Comment by Vierwood** [comment]
@Altemio I started an observe game from around the year 30 last night and it's still running without any crashes 900 years later.

Also, wow that's some border gore...

**Comment by Vierwood** [comment]
For some reason the Freehold is reverting to the original Chinese government, and after awhile the Western Valyrian Territories also become the Chinese government.

**Comment by tannerflick4** [comment]
Hmm I think @Altemio might have changed something with that recently. 

I would like help in getting the likes & dislikes to work! I cannot figure it out.
