### ISSUE TITLE
Offmap Valyrian Freehold

### ISSUE THREAD

**Issue by tannerflick4** [Altemio/SevenKingdoms-master#32]
2.8 & JD added the awesome new feature of offmap powers. Our Valyrian Freehold has to be totally adapted over so the mod runs fine & so all the features and options of the offmap feature work well.

I have worked through all of the common folder, as well as decisions, and am currently going through events. Vierwood is working through the history for us. 

I do think the crash we have now is related to something interface or graphics, because we have much of the necessary files made and corrected to give us the "screen" of the offmap power. 

While I will continue editing and working through these things, I would like help figuring out the crashes and/or errors I have made accidentally, or any ways to improve our code. 

This will be a running board we can use to discuss these things.

Thanks - tsf4

**Comment by tannerflick4** [comment]
The section of code in jd_sucession_events that starts the file I am definitely not sure of what it does.

Right now, I am going off what I think it does, which is give a new name to the freehold if Valyria is taken over by our world's khitans or jurchens - dothraki, rhoynish & ghiscari, plus some names for revolt/rebels taking over. Just noting this here in case I horribly scarred it.

**Comment by tannerflick4** [comment]
Another concern I have is in all this code I am not sure what should be the actual freehold vs the governor of the western territories, if any need to be the viceroy at all.

**Comment by tannerflick4** [comment]
Got the go-ahead from Knuckey to use the AGOT mod's names for our invader cultures

**Comment by ZeroFighterR** [comment]
That's good to hear

**Comment by tannerflick4** [comment]
Religions for eastern faiths have been added, but no need to give them secret religion code because I have added code where they cannot be made into someone's secret religion or have a cult.

**Comment by RowanMaBoot** [comment]
The off-map power might be causing the current build's crashing. Uncertain at this point.

[From Work]

**Comment by tannerflick4** [comment]
Closing this since just have loc to go, hopefully.
