### ISSUE TITLE
Question about English vs. American spelling

### ISSUE THREAD

**Issue by Cyrano7** [Altemio/SevenKingdoms-master#35]
The localization files are somewhat split about which spelling to use. For example honor vs. honour or traveling vs. travelling. The game seems to be mostly using American spelling though.

If American is the preferred spelling I will volunteer myself to switch everything over.

**Comment by tannerflick4** [comment]
@Cyrano7 I think American is preferred/intended.

**Comment by RowanMaBoot** [comment]
I've been writing in UK English (although I live in the US), but that is due to it being my native 'language' - and because honor doesn't look right at all to me. Mind I haven't done a whole lot localisation wise, so stuff written in UK English will be a rather small percentage of locals.

It's been an uphill battle, since both tanner and Vierwood are born-bred Americans (lingo and all), so if you think the spelling disparity is a big deal, you're free to do as you please with the spelling and use of words.

Oh and thanks for looking into our localisations, it's really appreciated! Not something we have a lot of time to dedicate ourselves to, despite its ability to enhance the feel of the mod.

**Comment by Cyrano7** [comment]
Oddly GRM uses American spelling but uses grey over gray.

**Comment by blackninja9939** [comment]
Vanilla aims for American so if you want to keep in line with future changes from vanilla then use American as well.

**Comment by Cyrano7** [comment]
Ya I am going to go american spelling on everything except for grey.

**Comment by Cyrano7** [comment]
@blackninja9939 are you still active with the Game of Thrones mod? I'd really like to do something similar for them as I play that mod a lot as well. There is a LOT more typos in those files, some which have been in the game for a long time.

**Comment by blackninja9939** [comment]
@Cyrano7 I am but if you did this stuff for AGOT it would be better sent to knuckey as I do not do much implementation work these days, hard to want to script in your free time when you do it at work 😬

**Comment by Cyrano7** [comment]
@blackninja9939 Ya I sent him a message awhile ago and never heard back. I guess they just use dropbox to work together so it might be hard to implement anyways. I've reported some stuff on the forums but there is so much it's kinda hard to get to without something like github.

**Comment by blackninja9939** [comment]
@Cyrano7 Yeah we do use dropbox, if you do this then send the files to me as a zip I will send to him

**Comment by Cyrano7** [comment]
@blackninja9939 If I use the localization files from the last release they probably won't match up with their current copies and there will be unintentional overrides.

I don't mean this in a judging way but is there any reason they don't use some sort of online version control?

**Comment by blackninja9939** [comment]
@Cyrano7 it'll probably be fine enough, can diff tool the changes we know are things we've touched

We have no real reason to, there is 2 of us doing it so no need to change over it all now. As for originally, git was not that big of a thing in non-programming circles but dropbox was a well known file sharing system.

**Comment by Cyrano7** [comment]
@blackninja9939 well this is what I have so far. It took more time to QC it then to do it. Over 1K line changes! I left things that GRM uses that are nonstandard like grey and foeman. I left flavor dialog too. I checked reddit and the forums for people reporting typos and wonky sentences and included those. I haven't included any punctuation spacing fixes though. I wish I could give it to you in smaller chucks so it's easier to review. Here: https://github.com/Cyrano7/Cyranos-AGOT-localization-files

**Comment by blackninja9939** [comment]
Cool, have messaged it to knuckey

**Comment by Cyrano7** [comment]
Awesome, Let me know how it goes. Might do some more soonish.
