### ISSUE TITLE
TODO: Duchy and Province Overhaul

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#4]
**Low Importance**

Long term plan is redo the shapes of many provinces and duchies.

Reason: Many of the provinces were put down at random, with no relation to locations of canon-cities and, biggest issue of all, what duchies they would be members of. You guys have probably noticed the messy state of some regions, especially over in Essos (!!!), the Crownlands and Dusklands.

North and Beyond are probably the only areas I don't desperately feel the need to touch up.

This is a low priority task, and will be done over the long term. Once we've got custom colours for the duchies and Kingdoms, this task should be far easier, as right now many of the duchies share similar colours.

Once rivers have been added (minor rivers), many provinces will need edits so to get them to follow rivers and other terrain features. The mountain regions need to be shrunk somewhat, as they occupy a lot of space. There is a certain area in the Westerlands, bordering the Reach, that looks rather bad.

Reshaping may result in long term balance changes of some duchies and provinces get moved around to neighbours.

**Comment by tannerflick4** [comment]
Of note: I changed Torrhen's Square and Deepwood Motte to be more accurate to their lore-wise location, and added Ironrath, which the Forresters will hold at some point.

**Comment by tannerflick4** [comment]
Updated Moat Cailin - put the towers under the county and changed names to replace those
Updated the Eyrie - put the waypoints up the mountain as baronies instead of provinces
Switched Harvest Hall and Nightsong
Added Starfall to the Red Mountains duchy and changed name of its former duchy to Blackmont.

**Comment by RowanMaBoot** [comment]
Closing this issue, superseded by issue #13
