### ISSUE TITLE
CK2 crashes in EVTNAMELoR.40

### ISSUE THREAD

**Issue by suokko** [Altemio/SevenKingdoms-master#42]
I tried to test how close to working is the master. I noticed quickly it crashes pretty soon after starting the game. I managed to trace the issue to EVTNAMELoR.40. CK2 is trying to find some province which doesn't exists. The handling code doesn't check for failure to find the province which then crashes whole game. Removing the event allowed me to continue playing the game without crash.

**Comment by RowanMaBoot** [comment]
Thanks - catching that will help move things along for @Vierwood @TitanRogue and @tannerflick4 as the crashing was preventing them from testing stuff.

Doesn't surprise me, as it was among one of the still-vanilla files (about half of the events are still unmodified vanilla events). It has now been removed from the current build.
