### ISSUE TITLE
Add Crossing over the Torrentine

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#55]
![image](https://user-images.githubusercontent.com/4649131/89831176-00ae9080-db23-11ea-8261-8800429eeaff.png)

Enhancement request - to add a crossing. Image describes the situation fairly well, and it does make for odd behaviour having to move so far around the river (bridges logically would be present.

**Comment by tannerflick4** [comment]
Where would the crossing go, what prov to and from? I can code it in, even if we don;t have a bridge per se yet.

**Comment by RowanMaBoot** [comment]
I've added it between North Carrion Pass and South Carrion Pass, kinda turning the region into an accessible but highly defensible 'alley'. If you're being attacked from the West, you can hold North Carrion Pass, whilst if you're being attacked from the East you can hold South.

That is if the war isn't lost due to ticking warscore however.
